buildVariable: false
familyName: Noto Sans Old Turkic
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 8282
    start: 8282
recipeProvider: noto
sources:
- NotoSansOldTurkic.designspace
