buildVariable: false
familyName: Noto Sans Old Turkic
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
    - start: 0x205A
      end: 0x205A
sources:
- NotoSansOldTurkic.designspace
